import { describe, it, beforeEach, expect } from 'vitest';
import initObjects from './setup/data.js';
import { reset } from './setup/setup.js';

describe('Backbone.Relational.Model', () => {
	beforeEach(initObjects);

	it('Return values: set returns the Model', () => {
		const personId = 'person-10';
		const person = new Person({
			id: personId,
			name: 'Remi',
			resource_uri: personId
		});

		const result = person.set({ name: 'Hector' });
		expect(result).toBe(person);
	});

	it('`clear`', () => {
		const person = new Person({ id: 'person-10' });

		expect(person).toBe(Person.findOrCreate('person-10'));

		person.clear();

		expect(person.id).toBeFalsy();
		expect(Person.findOrCreate('person-10')).toBeFalsy();

		person.set({ id: 'person-10' });

		expect(person).toBe(Person.findOrCreate('person-10'));
	});

	it('getRelations', () => {
		const relations = person1.getRelations();

		expect(relations.length).toBe(6);
		expect(_.every(relations, (rel) => rel instanceof Backbone.Relational.Relation)).toBe(true);
	});

	it('getRelation', () => {
		const userRel = person1.getRelation('user');

		expect(userRel).toBeInstanceOf(Backbone.Relational.HasOne);
		expect(userRel.key).toBe('user');

		const jobsRel = person1.getRelation('jobs');

		expect(jobsRel).toBeInstanceOf(Backbone.Relational.HasMany);
		expect(jobsRel.key).toBe('jobs');

		expect(person1.getRelation('nope') == null).toBe(true);
	});

	it('getAsync on a HasOne relation', () => {
		let errorCount = 0;
		const person = new Person({
			id: 'person-10',
			resource_uri: 'person-10',
			user: 'user-10'
		});

		expect(person.getIdsToFetch('user')).toEqual(['user-10']);

		let request = person.getAsync('user', {
			error: () => {
				errorCount++;
			}
		});

		expect(_.isObject(request) && request.always && request.done && request.fail).toBeTruthy();
		expect(window.requests.length).toBe(1);
		expect(person.get('user')).toBeInstanceOf(User);

		window.requests[0].error();
		_.last(window.requests).success();

		expect(person.get('user')).toBeFalsy();
		expect(errorCount).toBe(1);

		const person2 = new Person({
			id: 'person-11',
			resource_uri: 'person-11'
		});

		request = person2.getAsync('user');
		expect(window.requests.length).toBe(1);
	});

	it('getAsync on a HasMany relation', () => {
		let errorCount = 0;
		const zoo = new Zoo({
			animals: [{ id: 'monkey-1' }, 'lion-1', 'zebra-1']
		});

		expect(zoo.getIdsToFetch('animals')).toEqual(['lion-1', 'zebra-1']);

		// Case 1: separate requests for each model
		window.requests = [];

		let request = zoo.getAsync('animals', {
			error: () => {
				errorCount++;
			}
		});

		expect(_.isObject(request) && request.always && request.done && request.fail).toBeTruthy();
		expect(window.requests.length).toBe(2);
		expect(zoo.get('animals').length).toBe(3);

		window.requests[0].error();
		_.last(window.requests).success();

		expect(zoo.get('animals').length).toBe(2);
		expect(errorCount).toBe(1);

		window.requests = [];
		request = zoo.getAsync('animals');

		expect(window.requests.length).toBe(0);
		expect(zoo.get('animals').length).toBe(2);

		// Case 2: one request per fetch (generated by the collection)
		window.requests = [];
		errorCount = 0;

		zoo.get('animals').url = function (models) {
			const ids = _.map(models || [], (model) => (model instanceof Backbone.Model ? model.id : model));
			return '/animal/' + (ids.length ? 'set/' + ids.join(';') + '/' : '');
		};

		zoo.set({ animals: ['monkey-1', 'lion-2', 'zebra-2'] });

		expect(zoo.get('animals').length).toBe(1);

		window.requests = [];
		request = zoo.getAsync('animals', {
			error: () => {
				errorCount++;
			}
		});

		expect(_.isObject(request) && request.always && request.done && request.fail).toBeTruthy();
		expect(window.requests.length).toBe(1);
		expect(_.last(window.requests).url).toBe('/animal/set/lion-2;zebra-2/');
		expect(zoo.get('animals').length).toBe(1);

		_.last(window.requests).error();
		expect(window.requests.length).toBe(1);

		expect(zoo.get('animals').length).toBe(1);
		expect(errorCount).toBe(1);

		window.requests = [];
		request = zoo.getAsync('animals');

		expect(window.requests.length).toBe(1);
		expect(zoo.get('animals').length).toBe(1);

		window.requests[0].success([{ id: 'lion-2' }, { id: 'zebra-2' }]);
		expect(zoo.get('animals').length).toBe(3);

		window.requests = [];
		request = zoo.getAsync('animals', { refresh: true });

		expect(window.requests.length).toBe(1);
		expect(_.last(window.requests).url).toBe('/animal/set/monkey-1;lion-2;zebra-2/');
		expect(zoo.get('animals').length).toBe(3);

		window.requests[0].error();
		expect(zoo.get('animals').length).toBe(3);
	});

	it('getAsync', async () => {
		const zoo = Zoo.findOrCreate({ id: 'z-1', animals: ['cat-1'] });

		zoo.on('add:animals', (animal) => {
			animal.on('change:favoriteFood', () => {});
		});

		const outer = new Promise((resolve) => {
			zoo.getAsync('animals').done((animals) => {
				expect(animals).toBeInstanceOf(AnimalCollection);
				expect(animals.length).toBe(1);

				const cat = zoo.get('animals').at(0);
				expect(cat.get('name')).toBe('Tiger');

				cat.getAsync('favoriteFood').done((food) => {
					expect(food.get('name')).toBe('Cheese');
					resolve();
				});

				expect(window.requests.length).toBe(2);
				_.last(window.requests).respond(200, { id: 'f-2', name: 'Cheese' });
			});
		});

		expect(zoo.get('animals').length).toBe(1);
		expect(window.requests.length).toBe(1);
		expect(_.last(window.requests).url).toBe('/animal/cat-1');

		_.last(window.requests).respond(200, { id: 'cat-1', name: 'Tiger', favoriteFood: 'f-2' });

		await outer;
	});

	it('autoFetch a HasMany relation', () => {
		new Shop({
			id: 'shop-1',
			customers: ['customer-1', 'customer-2']
		});

		expect(requests.length).toBe(2);
		requests.length = 0;

		new Shop({
			id: 'shop-2',
			customers: ['customer-1', 'customer-3']
		});

		expect(requests.length).toBe(1);
	});

	it('autoFetch on a HasOne relation (with callbacks)', () => {
		new Shop({
			id: 'shop-3',
			address: 'address-3'
		});

		expect(requests.length).toBe(1);

		const res = { successOK: false, errorOK: false };

		requests[0].success(res);
		expect(res.successOK).toBe(true);
		requests.length = 0;

		new Shop({
			id: 'shop-4',
			address: 'address-4'
		});

		expect(requests.length).toBe(1);
		requests[0].error(res);
		expect(res.errorOK).toBe(true);
	});

	it('autoFetch false by default', () => {
		new Agent({
			id: 'agent-1',
			customers: ['customer-4', 'customer-5']
		});

		expect(requests.length).toBe(0);

		new Agent({
			id: 'agent-2',
			address: 'address-5'
		});

		expect(requests.length).toBe(0);
	});

	it('`clone`', () => {
		const user = person1.get('user');

		const newPerson = person1.clone();

		expect(newPerson.get('user')).toBe(null);
		expect(person1.get('user')).toBe(user);
	});

	it('`save` (with `wait`)', () => {
		const node1 = new Node({ id: '1', parent: '3', name: 'First node' });
		const node2 = new Node({ id: '2', name: 'Second node' });

		let request = node2.save('parent', node1, { wait: true });
		let json = JSON.parse(request.data);

		expect(_.isObject(json.parent)).toBe(true);
		expect(json.parent.id).toBe('1');
		expect(node2.get('parent')).toBe(null);

		request.success();

		expect(node2.get('parent')).toBe(node1);

		request = node2.save('parent', { id: '3', parent: '2', name: 'Third node' }, { wait: true });
		json = JSON.parse(request.data);

		expect(_.isObject(json.parent)).toBe(true);
		expect(json.parent.id).toBe('3');
		expect(node2.get('parent')).toBe(node1);

		request.success();

		const node3 = node2.get('parent');

		expect(node3).toBeInstanceOf(Node);
		expect(node3.id).toBe('3');

		request = node2.save('parent', node1, { wait: true });
		request.error();

		expect(node2.get('parent')).toBe(node3);

		const user1 = person1.get('user');
		request = person1.save('user', null, { wait: true });
		json = JSON.parse(request.data);

		expect(person1.get('user')).toBe(user1);

		request.success(json);

		expect(person1.get('user')).toBe(null);

		request = person1.save('user', user1, { wait: true });
		json = JSON.parse(request.data);

		expect(json.user_id).toBe(user1.id);
		expect(person1.get('user')).toBe(null);

		request.success(json);

		expect(person1.get('user')).toBe(user1);

		const zoo = new Zoo({ id: 'z1' });
		const animal1 = new Animal({ id: 'a1', species: 'Goat', name: 'G' });
		const coll = new Backbone.Relational.Collection([{ id: 'a2', species: 'Rabbit', name: 'R' }, animal1]);

		request = zoo.save('animals', coll, { wait: true });
		json = JSON.parse(request.data);

		expect(zoo.get('animals').length).toBe(0);

		request.success(json);

		expect(zoo.get('animals').length).toBe(2);
	});

	it('`Collection.create` (with `wait`)', () => {
		const nodeColl = new NodeList();
		let nodesAdded = 0;

		nodeColl.on('add', () => {
			nodesAdded++;
		});

		nodeColl.create({ id: '3', parent: '2', name: 'Third node' }, { wait: true });
		expect(nodesAdded).toBe(0);
		requests[requests.length - 1].success();
		expect(nodesAdded).toBe(1);

		nodeColl.create({ id: '4', name: 'Third node' }, { wait: true });
		expect(nodesAdded).toBe(1);
		requests[requests.length - 1].error();
		expect(nodesAdded).toBe(1);
	});

	it('`toJSON`: simple cases', () => {
		const node = new Node({ id: '1', parent: '3', name: 'First node' });
		new Node({ id: '2', parent: '1', name: 'Second node' });
		new Node({ id: '3', parent: '2', name: 'Third node' });

		const json = node.toJSON();

		expect(json.children.length).toBe(1);
	});

	it("'toJSON' should return null for relations that are set to null, even when model is not fetched", () => {
		let person = new Person({ user: 'u1' });

		expect(person.toJSON().user_id).toBe('u1');
		person.set('user', null);
		expect(person.toJSON().user_id).toBe(null);

		person = new Person({ user: new User({ id: 'u2' }) });

		expect(person.toJSON().user_id).toBe('u2');
		person.set({ user: 'unfetched_user_id' });
		expect(person.toJSON().user_id).toBe('unfetched_user_id');
	});

	it("`toJSON` should include ids for 'unknown' or 'missing' models (if `includeInJSON` is `idAttribute`)", () => {
		const zoo = new Zoo({ id: 'z1', animals: ['a1', 'a2'] });
		let zooJSON = zoo.toJSON();

		expect(_.isArray(zooJSON.animals)).toBe(true);
		expect(zooJSON.animals.length).toBe(0);

		new Animal({ id: 'a1' });
		zooJSON = zoo.toJSON();
		expect(zooJSON.animals.length).toBe(1);

		const agent = new Agent({ id: 'a1', customers: ['c1', 'c2'] });
		let agentJSON = agent.toJSON();

		expect(_.isArray(agentJSON.customers)).toBe(true);
		expect(agentJSON.customers.length).toBe(2);

		const c1 = new Customer({ id: 'c1' });
		expect(agent.get('customers').length).toBe(1);

		agentJSON = agent.toJSON();
		expect(agentJSON.customers.length).toBe(2);

		agent.set('customers', ['c1', 'c3']);
		new Customer({ id: 'c3' });

		agentJSON = agent.toJSON();
		expect(agentJSON.customers.length).toBe(2);

		agent.get('customers').remove(c1);

		agentJSON = agent.toJSON();
		expect(agentJSON.customers.length).toBe(1);

		const person = new Person({ id: 'p1', user: 'u1' });
		let personJSON = person.toJSON();

		expect(personJSON.user_id).toBe('u1');

		const u1 = new User({ id: 'u1' });
		personJSON = person.toJSON();
		expect(u1.get('person')).toBe(person);
		expect(personJSON.user_id).toBe('u1');

		person.set('user', 'u1');
		personJSON = person.toJSON();
		expect(personJSON.user_id).toBe('u1');

		u1.destroy();
		personJSON = person.toJSON();
		expect(u1.get('person')).toBeFalsy();
		expect(personJSON.user_id).toBe('u1');
	});

	it('`toJSON` should include ids for unregistered models (if `includeInJSON` is `idAttribute`)', () => {
		const person = new Person({ id: 'p1', user: 'u1' });
		let personJSON = person.toJSON();

		expect(personJSON.user_id).toBe('u1');

		const u1 = new User({ id: 'u1' });
		personJSON = person.toJSON();
		expect(u1.get('person')).toBe(person);
		expect(personJSON.user_id).toBe('u1');

		Backbone.Relational.store.unregister(u1);

		personJSON = person.toJSON();
		expect(personJSON.user_id).toBe('u1');
	});

	it('`parse` gets called through `findOrCreate`', () => {
		let parseCalled = 0;
		Zoo.prototype.parse = Animal.prototype.parse = function (resp) {
			parseCalled++;
			return resp;
		};

		const zoo = Zoo.findOrCreate(
			{
				id: '1',
				name: 'San Diego Zoo',
				animals: [{ id: 'a' }]
			},
			{ parse: true }
		);
		let animal = zoo.get('animals').first();

		expect(animal.get('livesIn')).toBeTruthy();
		expect(animal.get('livesIn')).toBeInstanceOf(Zoo);
		expect(animal.get('livesIn').get('animals').get(animal)).toBe(animal);

		expect(parseCalled).toBe(1);

		parseCalled = 0;

		animal = new Animal({ id: 'b' });
		animal.set(
			{
				id: 'b',
				livesIn: {
					id: '2',
					name: 'San Diego Zoo',
					animals: ['b']
				}
			},
			{ parse: true }
		);

		expect(animal.get('livesIn')).toBeTruthy();
		expect(animal.get('livesIn')).toBeInstanceOf(Zoo);
		expect(animal.get('livesIn').get('animals').get(animal)).toBe(animal);

		expect(parseCalled).toBe(0);

		Zoo.prototype.parse = Animal.prototype.parse = Backbone.Relational.Model.prototype.parse;
	});

	it('`Collection#parse` with RelationalModel simple case', () => {
		const Contact = Backbone.Relational.Model.extend({
			parse: function (response) {
				response.bar = response.foo * 2;
				return response;
			}
		});
		const Contacts = Backbone.Relational.Collection.extend({
			model: Contact,
			url: '/contacts',
			parse: function (response) {
				return response.items;
			}
		});

		const contacts = new Contacts();
		contacts.fetch({
			response: {
				status: 200,
				responseText: { items: [{ foo: 1 }, { foo: 2 }] }
			}
		});

		expect(contacts.length).toBe(2);
		const contact = contacts.first();
		expect(contact).toBeTruthy();
		expect(contact).toBeInstanceOf(Contact);
		expect(contact.get('foo')).toBe(1);
		expect(contact.get('bar')).toBe(2);
	});

	it('By default, `parse` should only get called on top-level objects; not for nested models and collections', () => {
		const companyData = {
			data: {
				id: 'company-1',
				contacts: [{ id: '1' }, { id: '2' }]
			}
		};

		const Contact = Backbone.Relational.Model.extend();
		const Contacts = Backbone.Relational.Collection.extend({
			model: Contact
		});

		const LocalCompany = Backbone.Relational.Model.extend({
			urlRoot: '/company/',
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'contacts',
					relatedModel: Contact,
					collectionType: Contacts
				}
			]
		});

		let parseCalled = 0;
		LocalCompany.prototype.parse =
			Contact.prototype.parse =
			Contacts.prototype.parse =
				function (resp) {
					parseCalled++;
					return resp.data || resp;
				};

		const company = new LocalCompany(companyData, { parse: true });
		const contacts = company.get('contacts');
		const contact = contacts.first();

		expect(company.id).toBe('company-1');
		expect(contact && contact.id === '1').toBe(true);
		expect(parseCalled).toBe(1);

		company.fetch({
			parse: true,
			response: {
				status: 200,
				responseText: _.clone(companyData)
			}
		});

		expect(parseCalled).toBe(2);

		expect(contacts).toBe(company.get('contacts'));
		expect(contacts.length).toBe(2);
		expect(contact && contact.id === '1').toBe(true);
		expect(contact).toBe(contacts.first());
	});

	it('constructor.findOrCreate', () => {
		const personColl = Backbone.Relational.store.getCollection(person1);
		const origPersonCollSize = personColl.length;

		let person = Person.findOrCreate(person1.id);

		expect(person).toBe(person1);
		expect(personColl.length).toBe(origPersonCollSize);

		person = Person.findOrCreate({ id: person1.id, name: 'dude' });

		expect(person.get('name')).toBe('dude');
		expect(person1.get('name')).toBe('dude');

		expect(personColl.length).toBe(origPersonCollSize);

		person = Person.findOrCreate({ id: 5001 }, { create: false });

		expect(person).toBeFalsy();
		expect(personColl.length).toBe(origPersonCollSize);

		person = Person.findOrCreate({ id: 5001 });

		expect(person).toBeInstanceOf(Person);
		expect(personColl.length).toBe(origPersonCollSize + 1);

		person = Person.findOrCreate({ id: person1.id, name: 'phil' }, { merge: false });

		expect(person.get('name')).toBe('dude');
		expect(person1.get('name')).toBe('dude');
	});

	it('constructor.find', () => {
		const person = Person.find({ id: 5001 });
		expect(person).toBeFalsy();
	});

	it('change events in relation can use changedAttributes properly', () => {
		const scope = {};
		Backbone.Relational.store.addModelScope(scope);

		scope.PetAnimal = Backbone.Relational.Model.extend({
			subModelTypes: {
				cat: 'Cat',
				dog: 'Dog'
			}
		});
		scope.Dog = scope.PetAnimal.extend();
		scope.Cat = scope.PetAnimal.extend();

		scope.PetOwner = Backbone.Relational.Model.extend({
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'pets',
					relatedModel: scope.PetAnimal,
					reverseRelation: {
						key: 'owner'
					}
				}
			]
		});

		const owner = new scope.PetOwner({ id: 'owner-2354' });
		const animal = new scope.Dog({ type: 'dog', id: '238902', color: 'blue' });
		expect(animal.get('color')).toBe('blue');

		let changes = 0;
		let changedAttrs = null;
		animal.on('change', (model) => {
			changes++;
			changedAttrs = model.changedAttributes();
		});

		animal.set({ color: 'green' });
		expect(changes).toBe(1);
		expect(changedAttrs.color).toBe('green');

		owner.set(
			owner.parse({
				id: 'owner-2354',
				pets: [{ id: '238902', type: 'dog', color: 'red' }]
			})
		);

		expect(animal.get('color')).toBe('red');
		expect(changes).toBe(2);
		expect(changedAttrs.color).toBe('red');
	});

	it('change events should not fire on new items in Collection#set', () => {
		let modelChangeEvents = 0;
		let collectionChangeEvents = 0;

		const Animal2 = Animal.extend({
			initialize: function () {
				this.on('all', (name) => {
					if (name.indexOf('change') === 0) {
						modelChangeEvents++;
					}
				});
			}
		});

		const AnimalCollection2 = AnimalCollection.extend({
			model: Animal2,

			initialize: function () {
				this.on('all', (name) => {
					if (name.indexOf('change') === 0) {
						collectionChangeEvents++;
					}
				});
			}
		});

		new Zoo({ id: 'zoo-1' });

		const coll = new AnimalCollection2();
		coll.set([
			{
				id: 'animal-1',
				livesIn: 'zoo-1'
			}
		]);

		expect(collectionChangeEvents).toBe(0);

		modelChangeEvents = collectionChangeEvents = 0;

		coll.at(0).set('name', 'Willie');

		expect(modelChangeEvents).toBe(2);
	});

	it("Model's collection children should be in the proper order during fetch w/remove: false", () => {
		const Child = Backbone.Relational.Model.extend();
		const Parent = Backbone.Relational.Model.extend({
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'children',
					relatedModel: Child
				}
			]
		});

		Child.findOrCreate({ id: 'foo1' });

		const parent = Parent.findOrCreate({ id: 'the-parent' });
		const children = parent.get('children');
		expect(children.length).toBe(0);
		parent.set(
			{
				id: 'the-parent',
				children: [{ id: 'foo1' }, { id: 'foo2' }]
			},
			{
				remove: false
			}
		);

		expect(children.length).toBe(2);
		expect(children.pluck('id')).toEqual(['foo1', 'foo2']);
	});
});

describe('Backbone.Relational.Model inheritance (`subModelTypes`)', () => {
	beforeEach(reset);

	it('Object building based on type, when using explicit collections', () => {
		const scope = {};
		Backbone.Relational.store.addModelScope(scope);

		scope.Mammal = Animal.extend({
			subModelTypes: {
				primate: 'Primate',
				carnivore: 'Carnivore',
				ape: 'Primate'
			}
		});
		scope.Primate = scope.Mammal.extend({
			subModelTypes: {
				human: 'Human'
			}
		});
		scope.Human = scope.Primate.extend();
		scope.Carnivore = scope.Mammal.extend();

		const MammalCollection = AnimalCollection.extend({
			model: scope.Mammal
		});

		const mammals = new MammalCollection([
			{ id: 5, species: 'chimp', type: 'primate' },
			{ id: 6, species: 'panther', type: 'carnivore' },
			{ id: 7, species: 'person', type: 'human' },
			{ id: 8, species: 'gorilla', type: 'ape' }
		]);

		expect(mammals.at(0)).toBeInstanceOf(scope.Primate);
		expect(mammals.at(1)).toBeInstanceOf(scope.Carnivore);
		expect(mammals.at(2)).toBeInstanceOf(scope.Human);
		expect(mammals.at(3)).toBeInstanceOf(scope.Primate);
	});

	it('Object building based on type, when used in relations', () => {
		const scope = {};
		Backbone.Relational.store.addModelScope(scope);

		const PetAnimal = (scope.PetAnimal = Backbone.Relational.Model.extend({
			subModelTypes: {
				cat: 'Cat',
				dog: 'Dog'
			}
		}));
		const Dog = (scope.Dog = PetAnimal.extend({
			subModelTypes: {
				poodle: 'Poodle'
			}
		}));
		const Cat = (scope.Cat = PetAnimal.extend());
		const Poodle = (scope.Poodle = Dog.extend());

		scope.PetPerson = Backbone.Relational.Model.extend({
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'pets',
					relatedModel: PetAnimal,
					reverseRelation: {
						key: 'owner'
					}
				}
			]
		});

		const petPerson = new scope.PetPerson({
			pets: [
				{ type: 'dog', name: 'Spot' },
				{ type: 'cat', name: 'Whiskers' },
				{ type: 'poodle', name: 'Mitsy' }
			]
		});

		expect(petPerson.get('pets').at(0)).toBeInstanceOf(Dog);
		expect(petPerson.get('pets').at(1)).toBeInstanceOf(Cat);
		expect(petPerson.get('pets').at(2)).toBeInstanceOf(Poodle);

		petPerson.get('pets').add([
			{ type: 'dog', name: 'Spot II' },
			{ type: 'poodle', name: 'Mitsy II' }
		]);

		expect(petPerson.get('pets').at(3)).toBeInstanceOf(Dog);
		expect(petPerson.get('pets').at(4)).toBeInstanceOf(Poodle);
	});

	it('Object building based on type in a custom field, when used in relations', () => {
		const scope = {};
		Backbone.Relational.store.addModelScope(scope);

		const Caveman = (scope.Caveman = Backbone.Relational.Model.extend({
			subModelTypes: {
				rubble: 'Rubble',
				flintstone: 'Flintstone'
			},
			subModelTypeAttribute: 'caveman_type'
		}));
		const Flintstone = (scope.Flintstone = Caveman.extend());
		const Rubble = (scope.Rubble = Caveman.extend());

		scope.Cartoon = Backbone.Relational.Model.extend({
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'cavemen',
					relatedModel: Caveman
				}
			]
		});

		const captainCaveman = new scope.Cartoon({
			cavemen: [{ type: 'rubble', name: 'CaptainCaveman' }]
		});

		expect(captainCaveman.get('cavemen').at(0)).not.toBeInstanceOf(Rubble);

		const theFlintstones = new scope.Cartoon({
			cavemen: [
				{ caveman_type: 'rubble', name: 'Barney' },
				{ caveman_type: 'flintstone', name: 'Wilma' }
			]
		});

		expect(theFlintstones.get('cavemen').at(0)).toBeInstanceOf(Rubble);
		expect(theFlintstones.get('cavemen').at(1)).toBeInstanceOf(Flintstone);
	});

	it("Automatic sharing of 'superModel' relations", () => {
		const scope = {};
		Backbone.Relational.store.addModelScope(scope);

		scope.PetPerson = Backbone.Relational.Model.extend({});
		scope.PetAnimal = Backbone.Relational.Model.extend({
			subModelTypes: {
				dog: 'Dog'
			},

			relations: [
				{
					type: Backbone.Relational.HasOne,
					key: 'owner',
					relatedModel: scope.PetPerson,
					reverseRelation: {
						type: Backbone.Relational.HasMany,
						key: 'pets'
					}
				}
			]
		});

		scope.Flea = Backbone.Relational.Model.extend({});

		scope.Dog = scope.PetAnimal.extend({
			subModelTypes: {
				poodle: 'Poodle'
			},

			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'fleas',
					relatedModel: scope.Flea,
					reverseRelation: {
						key: 'host'
					}
				}
			]
		});
		scope.Poodle = scope.Dog.extend();

		const dog = new scope.Dog({ name: 'Spot' });
		const poodle = new scope.Poodle({ name: 'Mitsy' });

		const person = new scope.PetPerson({
			pets: [dog, poodle]
		});

		expect(dog.get('owner')).toBe(person);
		expect(poodle.get('owner')).toBe(person);

		const flea = new scope.Flea({ host: dog });
		const flea2 = new scope.Flea({ host: poodle });

		expect(dog.get('fleas').at(0)).toBe(flea);
		expect(poodle.get('fleas').at(0)).toBe(flea2);
	});

	it("Initialization and sharing of 'superModel' reverse relations from a 'leaf' child model", () => {
		const scope = {};
		Backbone.Relational.store.addModelScope(scope);
		scope.PetAnimal = Backbone.Relational.Model.extend({
			subModelTypes: {
				dog: 'Dog'
			}
		});

		scope.Flea = Backbone.Relational.Model.extend({});
		scope.Dog = scope.PetAnimal.extend({
			subModelTypes: {
				poodle: 'Poodle'
			},
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'fleas',
					relatedModel: scope.Flea,
					reverseRelation: {
						key: 'host'
					}
				}
			]
		});
		scope.Poodle = scope.Dog.extend();

		scope.PetPerson = Backbone.Relational.Model.extend({
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'pets',
					relatedModel: scope.PetAnimal,
					reverseRelation: {
						type: Backbone.Relational.HasOne,
						key: 'owner'
					}
				}
			]
		});

		const poodle = new scope.Poodle({ name: 'Mitsy' });
		const dog = new scope.Dog({ name: 'Spot' });

		const person = new scope.PetPerson({
			pets: [dog, poodle]
		});

		expect(dog.get('owner')).toBe(person);
		expect(poodle.get('owner')).toBe(person);

		const flea = new scope.Flea({ host: dog });
		const flea2 = new scope.Flea({ host: poodle });

		expect(dog.get('fleas').at(0)).toBe(flea);
		expect(poodle.get('fleas').at(0)).toBe(flea2);
	});

	it("Initialization and sharing of 'superModel' reverse relations by adding to a polymorphic HasMany", () => {
		const scope = {};
		Backbone.Relational.store.addModelScope(scope);
		scope.PetAnimal = Backbone.Relational.Model.extend({
			subModelTypes: {
				dog: 'Dog',
				fish: 'Fish'
			}
		});

		scope.Fish = scope.PetAnimal.extend({});

		scope.Flea = Backbone.Relational.Model.extend({});
		scope.Dog = scope.PetAnimal.extend({
			subModelTypes: {
				poodle: 'Poodle'
			},
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'fleas',
					relatedModel: scope.Flea,
					reverseRelation: {
						key: 'host'
					}
				}
			]
		});
		scope.Poodle = scope.Dog.extend({});

		scope.PetPerson = Backbone.Relational.Model.extend({
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'pets',
					relatedModel: scope.PetAnimal,
					reverseRelation: {
						type: Backbone.Relational.HasOne,
						key: 'owner'
					}
				}
			]
		});

		const person = new scope.PetPerson({
			pets: [{ type: 'poodle', name: 'Mitsy' }]
		});
		const poodle = person.get('pets').first();
		expect(poodle.get('owner')).toBe(person);
	});

	it('Overriding of supermodel relations', () => {
		const models = {};
		Backbone.Relational.store.addModelScope(models);

		models.URL = Backbone.Relational.Model.extend({});

		models.File = Backbone.Relational.Model.extend({
			subModelTypes: {
				video: 'Video',
				publication: 'Publication'
			},

			relations: [
				{
					type: Backbone.Relational.HasOne,
					key: 'url',
					relatedModel: models.URL
				}
			]
		});

		models.Video = models.File.extend({});

		models.Publication = Backbone.Relational.Model.extend({
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'url',
					relatedModel: models.URL
				}
			]
		});

		models.Project = Backbone.Relational.Model.extend({
			relations: [
				{
					type: Backbone.Relational.HasMany,
					key: 'files',
					relatedModel: models.File,
					reverseRelation: {
						key: 'project'
					}
				}
			]
		});

		expect(models.File.prototype.relations.length).toBe(2);
		expect(models.Video.prototype.relations.length).toBe(1);
		expect(models.Publication.prototype.relations.length).toBe(1);

		new models.File();

		expect(models.File.prototype.relations.length).toBe(2);
		expect(models.Video.prototype.relations.length).toBe(2);
		expect(models.Publication.prototype.relations.length).toBe(2);

		const projectDescription = {
			name: 'project1',

			files: [
				{
					name: 'file1 - video subclass',
					type: 'video',
					url: { location: 'http://www.myurl.com/file1.avi' }
				},
				{
					name: 'file2 - file baseclass',
					url: { location: 'http://www.myurl.com/file2.jpg' }
				},
				{
					name: 'file3 - publication',
					type: 'publication',
					url: [
						{ location: 'http://www.myurl.com/file3.pdf' },
						{ location: 'http://www.anotherurl.com/file3.doc' }
					]
				}
			]
		};

		const project = new models.Project(projectDescription);
		const files = project.get('files');
		const file1 = files.at(0);
		const file2 = files.at(1);
		const file3 = files.at(2);

		expect(models.File.prototype.relations.length).toBe(2);
		expect(models.Video.prototype.relations.length).toBe(2);
		expect(models.Publication.prototype.relations.length).toBe(2);

		expect(_.size(file1._relations)).toBe(2);
		expect(_.size(file2._relations)).toBe(2);
		expect(_.size(file3._relations)).toBe(2);

		expect(file1.get('url')).toBeInstanceOf(Backbone.Model);
		expect(file1.getRelation('url')).toBeInstanceOf(Backbone.Relational.HasOne);

		expect(file3.get('url')).toBeInstanceOf(Backbone.Relational.Collection);
		expect(file3.getRelation('url')).toBeInstanceOf(Backbone.Relational.HasMany);
	});

	it('toJSON includes the type', () => {
		const scope = {};
		Backbone.Relational.store.addModelScope(scope);

		scope.PetAnimal = Backbone.Relational.Model.extend({
			subModelTypes: {
				dog: 'Dog'
			}
		});

		scope.Dog = scope.PetAnimal.extend();

		const dog = new scope.Dog({ name: 'Spot' });

		const json = dog.toJSON();

		expect(json.type).toBe('dog');
	});

	it('getAsync on an unknown relation key does not throw', () => {
		const zoo = new Zoo({ id: 'z-getasync-1', name: 'Artis' });

		expect(() => zoo.getAsync('thisIsNotARelation')).not.toThrow();
	});

	it("Model constructor does not mutate caller's options.collection", () => {
		const coll = new AnimalCollection();
		const sharedOpts = { collection: coll };

		new Animal({ id: 'a-mut-1' }, sharedOpts);

		expect(sharedOpts.collection).toBe(coll);
	});

	it('initializeRelations releases the semaphore even when a relation init throws', () => {
		let capturedModel = null;
		const orig = Backbone.Relational.store.initializeRelation;

		Backbone.Relational.store.initializeRelation = function (model) {
			capturedModel = model;
			throw new Error('simulated relation init failure');
		};

		try {
			try {
				new Zoo({ id: 'z-init-fail' });
			} catch {
				// expected to propagate
			}
		} finally {
			Backbone.Relational.store.initializeRelation = orig;
		}

		expect(capturedModel).toBeTruthy();
		expect(capturedModel.isLocked()).toBe(false);
	});
});
